name: Android CI

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 8512546
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: foo
      run: sudo apt-get install -y lib32z1
    - name: Build with Gradle
      run: ./gradlew build
